name: Tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install rye
        run: |
          curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash
          $HOME/.rye/shims/rye pin ${{ matrix.python-version }}
          $HOME/.rye/shims/rye sync

      - name: Lint
        run: $HOME/.rye/shims/rye run lint

      - name: Test
        run: $HOME/.rye/shims/rye run test

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
